services:
  - type: web
    name: ythls-fastapi # You can change this name if you want
    env: python
    plan: free # Use the free instance type
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port $PORT"
    healthCheckPath: /docs # A good path to check if the app is running
